### ISSUE TITLE
whiptail not found

### ISSUE THREAD

**Issue by micahflee** [scidsg/hushline#106]
I'm testing out the easy install (`curl -sSL https://install.hushline.app | bash`) in an Ubuntu docker container. I get this error:

```
root@b3d4f8372e0e:/# curl -sSL https://install.hushline.app | bash
  _    _           _       _      _            
 | |  | |         | |     | |    (_)           
 | |__| |_   _ ___| |__   | |     _ _ __   ___ 
 |  __  | | | / __| '_ \  | |    | | '_ \ / _ \
 | |  | | |_| \__ \ | | | | |____| | | | |  __/
 |_|  |_|\__,_|___/_| |_| |______|_|_| |_|\___|
                                               
🤫 Your anonymous tip line and suggestion box. 

A free tool by Science & Design - https://scidsg.org
bash: line 19: whiptail: command not found
You chose Cancel.
root@b3d4f8372e0e:/#       
```

If I install the `whiptail` package, it then works. (Likewise, on a totally fresh Ubuntu, I had to install the `curl` package too.)

Seems that if whiptail isn't installed, it should handle it better-- like, display instructions on how to install it for their OS.

Finishing the installation wizard, it seems I need these packages in ubuntu:

- `curl`
- `whiptail`
- `sudo`
- `git`
- `wget`

**Comment by glenn-sorrentino** [comment]
added a package install step in initial installer script! 

https://github.com/scidsg/hushline/commit/19136b09726e709affe4faeb71d8656adb79a666
