### ISSUE TITLE
Entering incorrect email password doesn't trigger an error message

### ISSUE THREAD

**Issue by sts10** [scidsg/hushline#112]
## What happened
During my first installation of Hush Line, I entered the password to the email address incorrectly (I entered the actual email account's password, rather than the generated app password). 

When I hit enter to submit this password, Hush Line never gave an error message of any kind. In fact, I made it through the entire installation process swimmingly, even receiving the nice `✅ Installation complete!` message in my Terminal at the end. 

However, when I went to send a test message through my up-and-running Hush Line form, I simply never received an email in my inbox. A real-world user who entered an incorrect password as I did would very likely just think they weren't getting any submissions to their Hush Line. 

## What I expected to happen

Ideally, the installing user would get an error message if they entered an incorrect password for the email account Hush Line is to use, the sooner the better.

## Possible solutions
Technically, I'm not sure how to "test" this correctness of the email password... maybe Hush Line itself sends a test/confirmation message itself at the end of the installation process and somehow checks if it was successful or not?

## Ability to troubleshoot

Even when I knew the problem -- that I had entered the wrong password -- I wasn't certain how to best fix the issue with my installation. I ended up simply running the installation script again, hoping for the best. I think this ended up working, but I think it hints at a need for some kind of option to edit your Hush Line configuration if/when needed?

**Comment by glenn-sorrentino** [comment]
Fixed - added a check for the creds that will loop the user back through the dialogs is it fails:

```
# Enter and test SMTP credentials
test_smtp_credentials() {
    python3 << END
import smtplib

def test_smtp_credentials(smtp_server, smtp_port, email, password):
    try:
        server = smtplib.SMTP_SSL(smtp_server, smtp_port)
        server.login(email, password)
        server.quit()
        return True
    except smtplib.SMTPException as e:
        print(f"SMTP Error: {e}")
        return False

if test_smtp_credentials("$NOTIFY_SMTP_SERVER", $NOTIFY_SMTP_PORT, "$EMAIL", "$NOTIFY_PASSWORD"):
    exit(0)  # Exit with status 0 if credentials are correct
else:
    exit(1)  # Exit with status 1 if credentials are incorrect
END
}

while : ; do  # This creates an infinite loop, which will only be broken when the SMTP credentials are verified successfully
    whiptail --title "Email Setup" --msgbox "Let's set up email notifications. You'll receive an encrypted email when someone submits a new message.\n\nAvoid using your primary email address since your password is stored in plaintext.\n\nInstead, we recommend using a Gmail account with a one-time password." 16 64
    EMAIL=$(whiptail --inputbox "Enter your email:" 8 60 3>&1 1>&2 2>&3)
    NOTIFY_SMTP_SERVER=$(whiptail --inputbox "Enter the SMTP server address (e.g., smtp.gmail.com):" 8 60 3>&1 1>&2 2>&3)
    NOTIFY_PASSWORD=$(whiptail --passwordbox "Enter the password for the email address:" 8 60 3>&1 1>&2 2>&3)
    NOTIFY_SMTP_PORT=$(whiptail --inputbox "Enter the SMTP server port (e.g., 465):" 8 60 3>&1 1>&2 2>&3)

    if test_smtp_credentials; then
        break  # If credentials are correct, break the infinite loop
    else
        whiptail --title "SMTP Credential Error" --msgbox "SMTP credentials are invalid. Please check your SMTP server address, port, email, and password, and try again." 10 60
    fi
done  # End of the loop
```
