### ISSUE TITLE
Effect of displaying email address and PGP fingerprint

### ISSUE THREAD

**Issue by sts10** [scidsg/hushline#113]
![circled-hushline-to](https://github.com/scidsg/hushline/assets/4871664/f82de295-67e7-4b74-81fb-55b6ad9c2e53)

I'm interested in the pros and cons of displaying the email address, PGP key fingerprint, and PGP key expiration date so prominently on the Hush Line form, especially from the prospective of a source who doesn't know what PGP is (a majority of expected sources, as I understand it). 

Pros:
* Shows, in a sense, where your message is going.

Cons:
* The displayed email address and PGP fingerprint is easily spoofed by an attacker. May in fact provide a false sense of security that the form is going to the right place.
* If submitter wants to send an image or file, they maybe simply email the email address in plaintext and _expect_ their message to still be encrypted.
* Submitter may be confused by the presence PGP fingerprint and expiration date.

## Alternatives

The source (submitter) doesn't really need to know that their message is being emailed. Thus I don't think we _need_ to display the receiving email address. Instead, we could have the Hush Line user, during the installation process, write a short sentence to display in place of their email address, which could serve as a customized prompt ("Tell X organization about Y", etc.).

**Comment by glenn-sorrentino** [comment]
Good questions to raise. @doctordiba and @Bodicea can we explore this question in our pilot questions?

**Comment by glenn-sorrentino** [comment]
Gonna close this here and add it to our research tracker.
