### ISSUE TITLE
FOSSTODON Sharing survey links: Hushline and OnionShare  for participant recruitment + data collection - on S&D social media

### ISSUE THREAD

**Issue by doctordiba** [scidsg/hushline#115]
Share links to the Husline and OnionShare surveys, for the purposes of participant recruitment and data collection. 

The links will bring individuals to the respective survey, which they can then complete. 

**FOSSTODON HUSHLINE**
Hushline is a secure, confidential information sharing tool. Did you know this existed?! 

Do you use something like this?
Do you wish you or your job had something like this?! 

Come share your thoughts with us in an anonymous 1 minute survey! 

https://cryptpad.fr/form/#/2/form/view/aznAzzpG6Fh3K1Dq0JjslCK-NmSugmfLTP7ej+SqRl0/

**Comment by doctordiba** [comment]
**FOSSTODON ONIONSHARE**
OnionShare is a tool that lets you do anonymous peer to peer file sharing, chatting, and onion site hosting! 

Do you use OnionShare? Do you use similar tools? Do you have thoughts about what you want from a tool like this, whether or not you use one?

If so, come share your thoughts with us in an anonymous 2 minute survey! 

https://cryptpad.fr/form/#/2/form/view/5x3kJpBhIH1TIiRO8LLs8-AEmVPD22y20PBoCNH9LEE/

**Comment by doctordiba** [comment]
![Image](https://github.com/scidsg/hushline/assets/132092852/dc7f0d69-d7dc-4575-861e-61256fa7e28b)

**Comment by doctordiba** [comment]
![Image](https://github.com/scidsg/hushline/assets/132092852/7502a097-05a6-4d68-bd1a-f11a2f3998db)

**Comment by glenn-sorrentino** [comment]
great, thanks!
