### ISSUE TITLE
Socializing research process - survey development (Hushline, OnionShare) via GitHub

### ISSUE THREAD

**Issue by doctordiba** [scidsg/hushline#116]
Providing documentation surrounding the research process involved in creating the surveys for HushLine and OnionShare. 

This document will provide rationale and process for documentation and visibility purposes regarding our methods.

**Comment by glenn-sorrentino** [comment]
Save to project-info repo in relevant directories!

**Comment by doctordiba** [comment]
@glenn-sorrentino  thank you! I can't make a folder (e.g. "Research"), but it would be great to have one. 

Alternatively, would it be ok if I added the text in a header section in the readme?

Just want to make sure I don't put this in the wrong spot!!
