### ISSUE TITLE
REDDIT Sharing survey links: Hushline and OnionShare  for participant recruitment + data collection - on S&D social media

### ISSUE THREAD

**Issue by doctordiba** [scidsg/hushline#117]
ISSUE -- the best looking place to share re TOR ... I think it violates the community rules (see image). 
Other ideas on where to post, or keep it to the S&D page?
 
@glenn-sorrentino 

Thanks!

**Comment by doctordiba** [comment]
![Image](https://github.com/scidsg/hushline/assets/132092852/3c7dd1d1-d2c1-407f-96af-35614a4bf3f8)

**Comment by doctordiba** [comment]
Additional Reddit communities to consider (thank you schlink!):
r/information_security
r/netsec
r/opensource
r/privacy
r/privacytoolsio
r/privacyguides
r/cybersecurity

**Comment by doctordiba** [comment]
Issues w/ posting to Reddit... cannot get "post" option to activate for posts directed to these communities; perhaps we need to be a member of the community first? I don't use Reddit to post *just for videogame help....* so I'm not sure on this one.

**Comment by glenn-sorrentino** [comment]
Yeah I think we should join the relevant communities. Chances are they might also have TOS stuff to consider, but the ones you highlighted looks like a great start.

**Comment by doctordiba** [comment]
**TAG LINE for REDDIT HUSH LINE:** "Hush Line - got thoughts about secure, confidential info sharing?"

**TAG LINE for REDDIT ONIONSHARE**: "OnionShare wants to hear from you! Got thoughts? Got 2 min? Come on over!"

Posts for Surveys made in the following communities today:

[ ] - **r/information_security**

**Unable to post to the following communities today:**

[ ] - r/netsec - _wanted video only_
[ ] - r/opensource - _ no links (community rule violation)_
[ ] - r/privacy - _only approved surveys allowed (community rule violation)_
[ ] - r/privacytoolsio - _unable to post links (community rule violation)_
[ ] - r/privacyguides -  unable to post surveys (community rule violation) 
[ ] - r/cybersecurity - _decided not to post - may violate community rule re advertising / self promotion?_
