### ISSUE TITLE
Use parenthesis to be more explicit in install script

### ISSUE THREAD

**Issue by sts10** [scidsg/hushline#132]
When I ran `scripts/install-tor-only.sh` through [shellcheck](https://www.shellcheck.net/), one of the things it flagged was this line: 

https://github.com/scidsg/hushline/blob/8e99dc04258ceed0a1783551f18a291a456acdb4/scripts/install-tor-only.sh#L145

Here's what shellcheck prints:
```
[Line 145:](javascript:setPosition(145, 10))
nginx -t && systemctl restart nginx || error_exit
         ^-- [SC2015](https://www.shellcheck.net/wiki/SC2015) (info): Note that A && B || C is not if-then-else. C may run when A is true.
```

My interpretation here is that shellcheck wants you to be more explicit about the order of operations, which we can do with parenthesis. 

My guess is that we want something like this:
```bash
(nginx -t && systemctl restart nginx) || error_exit
```
This makes more clear that if _either_ `nginx -t` or `systemctl restart nginx` return `false`, the code should run `error_exit`, which I think is the intention of this line of code. And shellcheck is happy with this line (no warning).

**Comment by glenn-sorrentino** [comment]
fixed
