### ISSUE TITLE
e-display install script assumes your working directory?

### ISSUE THREAD

**Issue by sts10** [scidsg/hushline#139]
I noticed here: 

https://github.com/scidsg/hushline/blob/68a55fe88502232c9dddf9c15e3261fe5476d772/scripts/waveshare-2_7in-eink-display.sh#L31-L32

That this script will `git clone` this e-Paper repo down to wherever the user happens to run the script from. 

Should we have a `cd [somewhere]` command above this `git clone` call, so we're sure of where it's being cloned to, regardless of what working directory the user is in, like we do with with [Hush Line's general install script](https://github.com/scidsg/hushline/blob/main/scripts/install.sh#L30-L31)? Or `pip install` it to an absolute path, as we do with [Blackbox](https://github.com/scidsg/blackbox/blob/main/v2/display.sh#L15)?

**Comment by glenn-sorrentino** [comment]
fixed - cd'ing to `$HOME/hushline` before cloning waveshare repo
