### ISSUE TITLE
Add commit hash to QA table?

### ISSUE THREAD

**Issue by sts10** [scidsg/hushline#168]
https://github.com/scidsg/hushline/blob/bf77df592cbdbd066e58c39b4ed4d14b0145d242/README.md?plain=1#L36-L44

In the QA table, it might be useful to include the hash of the most recent commit for each QA install/run. 

For example, if I was to do a test install right now, I'd mark the date Nov 1, but we might have multiple commits throughout today. A more exact measure of the state of the project at a given time is the hash of the last commit. Right now, for example, that would be bf77df592cbdbd066e58c39b4ed4d14b0145d242. (GitHub is good about automatically making these in to links.) Maybe "Last commit" could be a new column in the QA table?

**Comment by glenn-sorrentino** [comment]
Yeah I like it - wanna add a column with the hash?
