### ISSUE TITLE
[Website]Certificate error: URL to request invitation not working. 

### ISSUE THREAD

**Issue by stepaola** [scidsg/hushline#239]
**Describe the bug**
The invitation page is not being displayed. There may be a security certificate error.

**To Reproduce**
1. Go to https://beta.hushline.app/submit_message/hushline-beta
2. See error

**Expected behavior**
Visit the page to request an invitation.

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.2.1
 - Browser: Firefox
 - Version 122.0.1

**Comment by glenn-sorrentino** [comment]
Not able to reproduce.

![Screenshot 2024-03-04 at 11 09 22 AM](https://github.com/scidsg/hushline/assets/28545431/8b0b69b7-217e-4c71-a6c1-d49a9a62b03d)

**Comment by glenn-sorrentino** [comment]
For coverage, @iAnonymous3000 can you test the URL, too?

**Comment by iAnonymous3000** [comment]
I am not able to reproduce it either.

OS: Pop!_OS 22.04 LTS
Browser: Brave v1.63.165

![image](https://github.com/scidsg/hushline/assets/32236127/b1c73e9f-b6d2-4d64-a6b1-21ebdf06e0db)

Browser: Firefox v123.0 

![Screenshot from 2024-03-04 14-17-42](https://github.com/scidsg/hushline/assets/32236127/038e7312-534f-4322-a370-c30ae1a453bd)

**Comment by stepaola** [comment]
For some reason I can't access the URL with my Brazilian IP. With VPN in the United States it works normally.
