### ISSUE TITLE
User IP Address Exposed to ISP in Message Submission Form; Add Indicator and Privacy Recommendations

### ISSUE THREAD

**Issue by iAnonymous3000** [scidsg/hushline#257]
During the privacy review of the Hush Line application, it was identified that users' web activities, including their visits to the Hush Line website, can be tracked by their Internet Service Providers (ISPs). While Hush Line does not store or log any user IP addresses or other Personally Identifiable Information (PII), ISPs' ability to monitor and track user web activity poses a significant privacy risk.

Expected Behavior:
Users should have the ability to access the Hush Line website and use the platform anonymously, without their web activities being tracked by their ISPs. The application should provide clear guidance to users on how to protect their privacy and anonymity while using the internet.

Actual Behavior:
When users access the internet, including visiting the Hush Line website, their web activities can be monitored and tracked by their ISPs. This tracking may include recording the websites visited, timestamps, and other metadata, which can potentially be used to profile users and compromise their privacy.

Impact:
The tracking of user web activity by ISPs poses a significant privacy risk, as it can reveal sensitive information about users' online behaviors, interests, and communication patterns. This risk extends beyond the Hush Line platform and affects users' overall online privacy. It is important to educate users about this risk and provide them with recommendations on how to protect their privacy while using the internet.

Proposed Solution:
1. Implement a mechanism to detect whether the user is accessing the Hush Line website through the VPN/Tor network.
2. Display a prominent indicator on the website, similar to the one in the provided image, showing the user's Tor usage status. For example:
   - If the user is accessing the site through Tor, display a message like "Using Tor for enhanced privacy".
   - If the user is not using Tor, display a message like "Not using Tor. Consider using Tor for improved privacy."
3. Include a link or button next to the Tor usage indicator that directs users to a dedicated page or section of the website providing more information about Tor and its benefits for online privacy.
4. On the dedicated Tor information page, provide clear instructions on how to download and use the Tor browser, along with explanations of how Tor helps protect user privacy by hiding IP addresses and encrypting traffic.
5. Include additional recommendations and best practices for enhancing online privacy, such as using trusted VPN services, privacy-focused browsers, and browser extensions that block tracking scripts.
6. Regularly review and update the privacy recommendations and instructions to ensure they align with the latest privacy threats and best practices.

Benefits:
- Raises user awareness about the importance of online privacy and the role of Tor in enhancing anonymity.
- Encourages users to adopt privacy-enhancing tools like Tor, empowering them to take control of their online privacy.
- Provides users with easily accessible information and instructions on how to use Tor and other privacy tools effectively.
- Demonstrates Hush Line's commitment to user privacy and security, building trust and fostering a privacy-conscious community.

![Screenshot from 2024-03-11 15-11-14](https://github.com/scidsg/hushline/assets/32236127/1418e419-6e71-45e8-873d-c2762eac4fa0)

**Comment by glenn-sorrentino** [comment]
Closed with #259
