### ISSUE TITLE
Avoid setting global config variables that are not otherwise referenced

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#273]
https://github.com/scidsg/hushline/blob/75ee6e0e58e71f014aedf4381dbd377d38691de7/app.py#L63-L66

We can directly create the `Flask-SqlAlchemy` config from env vars rather than creating temporary vars. We can also just set the config directly via an env var called `DB_URI` or something.

We may however want to create our own `Config` python object that pulls env vars and pre-processes them for us then dumps them into `Flask`'s config after munging.

**Comment by brassy-endomorph** [comment]
A further note on this is that it is an anti-pattern in Flask since the idea being that one process could have multiple Flask apps with different configurations. These values (and others like the currently global `fernet`) should be bound to the app itself using the extension pattern.

**Comment by glenn-sorrentino** [comment]
@brassy-endomorph It looks like you may have addressed this one already? I'm not seeing those config variables in the current codebase.

**Comment by brassy-endomorph** [comment]
No, this has not been addressed yet. There are definitely some that are still there, and we don't have a unified way of setting configurations.

**Comment by glenn-sorrentino** [comment]
Closed with #301

**Comment by brassy-endomorph** [comment]
This issue is not closed.

https://github.com/scidsg/hushline/blob/910ad8649a19f3c112e3db396edcdd2ec8001fa7/hushline/crypto.py#L6-L11
