### ISSUE TITLE
`get_client_ip` method allows attackers to spoof IP addresses

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#274]
https://github.com/scidsg/hushline/blob/75ee6e0e58e71f014aedf4381dbd377d38691de7/app.py#L572-L600

First, why aren't we using [`Request.remote_addr`](https://flask.palletsprojects.com/en/3.0.x/api/#flask.Request.remote_addr)

Second, we should be using [`ProxyFix`](https://werkzeug.palletsprojects.com/en/3.0.x/middleware/proxy_fix/#werkzeug.middleware.proxy_fix.ProxyFix) so that we can configure a trustable number of proxies for different `X-Forwarded-*` headers. This app will not run directly against the internet and with at the very least be behind a WSGI server (which may or may not modify these headers), and it may be something complex like "CloudFlare -> reverse proxy -> WSGI server -> flask" which will mean we have to be very careful about what we set.

But maybe even most importantly... why are we using this at all? It seems the only reason it's used is in the following template:

https://github.com/scidsg/hushline/blob/75ee6e0e58e71f014aedf4381dbd377d38691de7/templates/submit_message.html#L39

A user is not going to know their IP address, and that information maybe isn't even useful to them at all. Are they going to know if they're connecting over the clearnet or Tor by IP address alone? Probably not. This feature should probably be entirely removed, but if there is a reason for it, it is incorrectly implemented.

**Comment by glenn-sorrentino** [comment]
The feature is primarily for user education. The Learn More link takes the user to documentation about what this means. 

The thought is that if the user loads the same page in Tor Browser, they'll see a change in the listed IP. 

In the spirit of not adding features before they're tested, I'll remove it for now.
