### ISSUE TITLE
Use stronger algorithm for hashing passwords

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#276]
We may want to use `scrypt` or `argon2i` so we can control the memory hardness or number of threads to hash a password as a means to increase the difficulty of cracking passwords should the DB ever get leaked.

**Comment by brassy-endomorph** [comment]
Reopening this because `passlib` just wraps and uses `bcrypt`. It gives us a path forward to to updating the password hashes and migrating, but it doesn't actually change the underlying hashing function.

**Comment by glenn-sorrentino** [comment]
Do you have a preference for algorithms? Initial research for Argon2, aside from them winning the 2015 password hashing comp, its newer tech and uses more memory. Scrypt is faster and stronger against brute force.

**Comment by glenn-sorrentino** [comment]
I actually noticed that you recommended Argon2i. Is a middle ground 2id?

**Comment by glenn-sorrentino** [comment]
Working in the `hashing` branch: https://github.com/scidsg/hushline/blob/hashing/hushline/model.py

**Comment by brassy-endomorph** [comment]
After our out-of-band conversation, I think we should pause this so that we can figure out what the appropriate level of compute should, pending threat modeling. If we're not terribly concerned with APT threats, we can use something less complex.

Depends on #265
