### ISSUE TITLE
Reconsider database backend choice

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#277]
The app is currently using MariaDB, but it might just as well use Postgres or Sqlite. Was there a specific reason that MariaDB was chosen over Postgres? I know that MariaDB does not have fully atomic DDL within transactions which is a feature we're very much going to want when we start adding migrations. Also, Sqlite is tiny and fast and likely sufficient for our needs. It creates a smaller attack surface for the app, although it allows for less fine grained control of permissions for example.

**Comment by glenn-sorrentino** [comment]
Not a specific reason, but using Sqlite instead sounds great to me.

**Comment by iAnonymous3000** [comment]
I believe using SQLite as the database backend is a great idea for the following reasons:
- SQLite is likely to offer sufficient performance and functionality, effectively handling low to medium traffic.
- It creates a smaller attack surface compared to a full-fledged database server, which is beneficial from a security perspective.

While starting with SQLite, it's important to keep the option open to migrate to a more advanced database like PostgreSQL if the need arises.

This approach allows us to focus on building the core functionality of Hushline without getting bogged down in database administration overhead.
