### ISSUE TITLE
User and SecondaryUser are ambiguous

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#279]
Without docs, it's not immediately clear what a `User` vs. a `SecondaryUser` are. It _seems_ like one is `Admin` and the other is `Source` (or `Leaker` or whatever). The names should more accurately reflect what they are and do.

**Comment by glenn-sorrentino** [comment]
Yeah, the `SecondaryUser` table is actually for secondary usernames. 

It's a paid feature tailored for organizational use cases with the ability to add up to 5 additional usernames so they can all be managed from the same account.
