### ISSUE TITLE
App import should not list GPG keys

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#280]
It is unclear why this is happening despite the code comment, and we likely do not want to list keys like this. If we need to, we can hide it behind a `Click` command optionally gated behind a debug env var so like `HUSHLINE_DEBUG_OPTS=1 flask debug list-keys` or something.

https://github.com/scidsg/hushline/blob/75ee6e0e58e71f014aedf4381dbd377d38691de7/app.py#L778-L779

**Comment by glenn-sorrentino** [comment]
Closed by #292
