### ISSUE TITLE
Enable git-lfs for images

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#297]
This is mostly to keep clones small and because docs requires a lot of images.

LFS docs: https://git-lfs.com/

**Comment by glenn-sorrentino** [comment]
Closes with https://github.com/scidsg/hushline/commit/96e43863f096e4bb504e402779a8bcfc9bbacd07

Enabled Git Large File Storage for managing image files in the documentation directory.

This update includes:

- Configuration of Git LFS to track .png, .jpg, and .gif files within the docs/ directory and its subdirectories, ensuring large images are stored separately from the repository.
- Addition and customization of the .gitattributes file to specify LFS tracking rules for the targeted image files.
- [TODO] Documentation updates to guide contributors on installing Git LFS on their machines for seamless collaboration and interaction with LFS-tracked files.

This change addresses the need for keeping the repository size manageable, enhancing clone/pull speeds, and improving overall collaboration efficiency.
