### ISSUE TITLE
Dev environment should be easily startable

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#315]
I want to be able to hit `make run` and have the app start without any configuration or futzing.

Things that currently prevent this:

- We have a dependency on Redis for rate limiting. This should be configurable via env vars so that we can use local in-memory caching for dev at least.
- We use `dotenv` to load env vars that have to be manually populated. These env vars can be populated via the `Makefile` for now. (So related, we should yank `dotenv` as a loader for env vars as this encourages us to store secrets in a directory managed by `git`

There are probably more, and someone working on this will figure them out

**Comment by glenn-sorrentino** [comment]
Working here: https://github.com/scidsg/hushline/tree/dev-env

**Comment by glenn-sorrentino** [comment]
@brassy-endomorph I added our variables from .env into the makefile. While this is good for dev environments, how should we store this info for production? You mentioned Ansible before. Another solution could be to use a service file until we make that change.

**Comment by brassy-endomorph** [comment]
For production, we can add this to the service file:

```ini
[Service]
...
EnvironmentFile=/etc/hushline/hushline.conf
```

**Comment by glenn-sorrentino** [comment]
I'm also exploring Ansible for config management, with using their vault for secret storage.

**Comment by glenn-sorrentino** [comment]
@brassy-endomorph - The makefile works and executing `make run` launches the app locally.

![Screenshot 2024-04-02 at 1 17 43 PM](https://github.com/scidsg/hushline/assets/28545431/7bb904fd-ff09-4a03-ac39-84dd736ca0c8)

![Screenshot 2024-04-02 at 1 17 49 PM](https://github.com/scidsg/hushline/assets/28545431/d8687b75-67e4-4050-907e-840f3e92480a)
