### ISSUE TITLE
Flash Message Animation

### ISSUE THREAD

**Issue by glenn-sorrentino** [scidsg/hushline#388]
**Describe the bug**
When the user logging outs or updating their settings, a Flash message displays providing relevant feedback messages. `👋 You have been logged out successfully.`, for example. 

The message animates into the UI smoothly from the top of the viewport. When it animates out I intended for the message to animate out in reverse. While it technically does this, the animation is a little janky since it changes the z-index at the end: https://github.com/scidsg/hushline/blob/main/hushline/static/css/style.css#L254C1-L282C2 

```
@keyframes fadeInDown {
    0% {
        top: 0px;
        opacity: 0;
    }

    100% {
        top: 1rem;
        opacity: 1;
    }
}

@keyframes fadeOutUp {
    0% {
        top: 1rem;
        opacity: 1;
    }

    99% {
        top: 0;
        opacity: 0;
    }

    100% {
        opacity: 0;
        z-index: -999;
    }

}
``` 

**To Reproduce**
1. Go to `beta.hushline.app` and create an account.
2. Log in, then log out.

**Expected behavior**
A smooth animation in and out without the need to change the z-index as it does now.

**Screenshots**
![flash-message](https://github.com/scidsg/hushline/assets/28545431/53f8a53d-5432-475e-9921-f3587bb795fe)

**Desktop (please complete the following information):**
 - OS: Mac 14.5
 - Browser: Firefox, Safari
 -

**Comment by ispykenny** [comment]
This issue has been closed in PR https://github.com/scidsg/hushline/pull/394
