### ISSUE TITLE
Update Directory Checkbox to Toggle

### ISSUE THREAD

**Issue by glenn-sorrentino** [scidsg/hushline#389]
**Is your feature request related to a problem? Please describe.**
The settings screen uses a checkbox for users to opt-in to the directory. It feels dated and requires the user to also press a button to submit the form.

**Describe the solution you'd like**
Update the checkbox to appear as a toggle, where toggling auto-saves the form without the need for an explicit button.

**Design**
![Slice 1](https://github.com/scidsg/hushline/assets/28545431/128eb71d-818d-4dfe-93c7-d7daf465ca86)

**Comment by ispykenny** [comment]
Resolved in PR https://github.com/scidsg/hushline/pull/396
