### ISSUE TITLE
Better Email Forwarding

### ISSUE THREAD

**Issue by glenn-sorrentino** [scidsg/hushline#401]
In the beta, the lowest enrollment numbers were SMTP, presenting a problem with our goals of being a service you can set and forget. Currently, SMTP is a manual operation, and tailored more toward expert users rather than professionals in their respective fields - meaning generally non-technical.

## Acceptance Criteria

To make message forwarding more usable, we should do the following:

1. Use RiseUp.net's mail servers. We have our DNS updated with RiseUp's `MX` records and have set up the mailback address `notifications@hushline.app`. To the end user, they just see a `To:` field in the Message Forwarding section. 
2. If the user chooses to use custom SMTP, they may toggle on an Advanced section which reveals the current set of SMTP fields (`SMTP Username`, `SMTP Password`, `SMTP Address`, `SMTP Port`).
3. A user may only add a forwarding address if a PGP key has been added.
4. Removing the key removes the forwarding section.
5. RiseUp integration is only applicable for the managed service. The Personal Server will only use custom settings.

### Variables
1. We should move the variables to the Terraform Cloud.
```
SMTP Username:
SMTP Password:
SMTP Address: mail.riseup.net
SMTP Port: 465
```

### Design
![mailgun](https://github.com/scidsg/hushline/assets/28545431/3eef8aad-ac26-4737-87f7-78979a24a2f9)

**Comment by glenn-sorrentino** [comment]
Forward Email is an open-source managed service.
https://forwardemail.net/en/private-business-email?pricing=true

**Comment by glenn-sorrentino** [comment]
Upon further investigation, we should integrate RiseUp.net services with a custom mail domain.

**Comment by jeremywmoore** [comment]
@glenn-sorrentino on the last mock-up, what does it mean if a user has email forwarding configured for an that differs from the SMPT username? Should we remove the username and just use the forwarding address as the username?

**Comment by glenn-sorrentino** [comment]
> @glenn-sorrentino on the last mock-up, what does it mean if a user has email forwarding configured for an that differs from the SMPT username? Should we remove the username and just use the forwarding address as the username?

A `To:` addresses can either be the same or different from the `SMTP Username:` address, but it won't always be true that the `SMTP Username:` will be the same as the `To:` address. So for that last mockup, two scenarios:
1. Someone might want to use the Gmail SMTP settings, but have the delivery address sent to Protonmail.
2. Someone might want to use the Gmail SMTP settings and have messages sent to Gmail.

Right now we actually use the `SMTP Username:` value for the `To:` field, but it's actually limiting and doesn't meet the first case above.

In the background when we integrate RiseUp (at least in my quick experiments), the SMTP fields as they exist, which will be in an advanced section, will actually use our RiseUp credentials. The `From:` field will be `notifications@hushline.app`, which'll be invisible to the user.

**Comment by jeremywmoore** [comment]
Regarding the PGP key requirement for email-forwarding, should removing a pgp key disable forwarding? Alternatively, we could prevent removing a pgp key if forwarding is enabled.

**Comment by glenn-sorrentino** [comment]
I like first option - disable forwarding if the key is removed.
