### ISSUE TITLE
Admin tab in settings not loading new data

### ISSUE THREAD

**Issue by glenn-sorrentino** [scidsg/hushline#421]
Current Behavior:
Clicking on the Admin tab in Settings doesn't load any new content.

Expected:
Clicking on the Admin tab should show admin-specific content. 

https://github.com/user-attachments/assets/67c0c6c8-8eb7-4084-b7d2-eef1856b6fab

**Comment by ispykenny** [comment]
https://github.com/scidsg/hushline/pull/422
