### ISSUE TITLE
Username Aliases

### ISSUE THREAD

**Issue by glenn-sorrentino** [scidsg/hushline#498]
**Motivation**
Users will have reasons to have multiple tip lines, including different organizational departments, companies, or roles. Currently a user must create multiple accounts, which creates significant load, especially when looking for one message in particular.

**Acceptance Criteria**
- In the Settings UI, a paid user can add up to 5 aliases for the pro/Personal Server tiers, and 20 for business. 
- Users can edit or delete aliases
- Aliases have their own submit_message page
- Messages in the unified inbox include a badge showing to which account the message was sent.

**Comment by glenn-sorrentino** [comment]
Depends on #364

**Comment by brassy-endomorph** [comment]
Just to confirm some things:

1. A user is uniquely defined by an username _only_. (I think it should be by email address only, but that's another matter)
2. A user's primary username is no more or less special than an alias / secondary username
3. For a submitter, in the directory UI, primary and secondary usernames / profiles should be indistinguishable
4. All the fields/labels are unique per username, as in if I have `website=example.com` for one alias, then that will not appear on other aliases, and other aliases can have a different `website=example2.com`
5. Aliases have no email address tied to them, and any outbound emails or use of the email address would be sent to the associated primary user's email address

**Comment by glenn-sorrentino** [comment]
The use case to frame these questions with is that of a business with multiple departments requiring a tip line. We'll call it Vandelay Industries, and HR, Legal, and Finance who need additional tip lines.

> Just to confirm some things:
> 
> 1. A user is uniquely defined by an username _only_. (I think it should be by email address only, but that's another matter)

And ID

> 2. A user's primary username is no more or less special than an alias / secondary username

The initial account should be considered the "main" account for Vandelay Industries. Aliases/secondary usernames would be for departments like HR, Legal, and Finance.

> 3. For a submitter, in the directory UI, primary and secondary usernames / profiles should be indistinguishable

For a submitter, it should be clear which department they're messaging, so should be very distinguishable. Every alias has it's own page, bio, links, and directory listing.

![aliases](https://github.com/user-attachments/assets/4a53f3ac-8d72-4e81-9c1b-f0b3fd93d11c)

> 4. All the fields/labels are unique per username, as in if I have `website=example.com` for one alias, then that will not appear on other aliases, and other aliases can have a different `website=example2.com`

Correct

> 5. Aliases have no email address tied to them, and any outbound emails or use of the email address would be sent to the associated primary user's email address

Aliases have the option of using the primary email or a new one.

**Comment by brassy-endomorph** [comment]
For point 3, I meant a user should not be able to tell if they're messaging a primary account or a secondary alias. That should be transparent, correct?

**Comment by glenn-sorrentino** [comment]
> For point 3, I meant a user should not be able to tell if they're messaging a primary account or a secondary alias. That should be transparent, correct?

I think we should probably think about ways to concatenate the primary account name and secondary username, or make it primary + secondary in the display.

**Comment by brassy-endomorph** [comment]
Should display names be globally unique?

Should the username of the owner of an alias be displayed on directory? How should this be handled?

**Comment by brassy-endomorph** [comment]
@glenn-sorrentino on the alias overview page, on the list of aliases, there's a right pointing arrow. Is there something like `fontawesome` (or FOSS-ier version) you want to use? Or what should asset be?
