### ISSUE TITLE
Create a dev data script that populates the app with some reasonable defaults to speed up dev

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#552]
**Is your feature request related to a problem? Please describe.**

I want the app to be fully usable with one command so that I can test UI features or styling without having to manually click a bunch of things or run a bunch of CLI commands to get the app into a "normal production state."

**Describe the solution you'd like**

We should have one `dev_data.py` that assumes an empty migrated database and adds a few entries of all possible types. This should be outside the normal source directory so that it's not accidentally packaged and distributed in python packages, docker container, etc.

**Describe alternatives you've considered**

Clicking buttons, but I hate that. I guess also a SQL script that just gets exec'd, but that is much more tedious and brittle, and it would be harder to read than Python.

**Comment by glenn-sorrentino** [comment]
I believe this has been addressed, @brassy-endomorph
