### ISSUE TITLE
Rename "Vision" in nav bar

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#565]
**Is your feature request related to a problem? Please describe.**

The word "vision" is ambiguous in the nav bar. I assumed it would link to a page with info about Hushline's vision. Someone who wants computer vision to detect text probably wouldn't think to click that as most people don't even call it computer vision.

**Describe the solution you'd like**

This feature should probably be listed on the submissions page. In the nav bar, maybe name it "Image text reader" idk. I don't have a good answer.

**Comment by glenn-sorrentino** [comment]
I'm okay with Vision since it's an OCR feature. It's a feature for lawyers or journalists who receive photos and need an easy way to see what's there without manually scanning. Closing this until we learn if the naming is a problem with users.
