### ISSUE TITLE
Message Replies

### ISSUE THREAD

**Issue by glenn-sorrentino** [scidsg/hushline#631]
## Use Cases

- As a **tip line owner**, I need to reply to a whistleblower's message directly inside of Hush Line, so that the source knows the status of their disclosure.
- As a **whistleblower**, I need to know if my message has been received and its status, so that I know if I should look elsewhere to get help.

## Requirements

**Whistleblower**
- When an **unauthenticated** user submits a tip, a dynamic message URL is automatically created for them to the effect of `https://tips.hushline.app/to/Ungrouped-Headphones-Aluminum-9`
- A modal opens which gives the whistleblower a message containing their auto-generated URL.
- Clicking Continue redirects the whistleblower to the message page.
- The whistleblower only has access to this page. The global nav removes everything except the Directory and Donation links.

**Tip Line Owner**
- New messages receive an autogenerated name
- Drilling-in to a message shows the message metadata, encrypted contents, and a case status menu button. 
- Changing the case's status sends a predefined reply visible on the message page to both tip line owner and whistleblower.

### Whistleblower

**Step 1: Send a message**
When an unauthenticated user submits a new message, a modal opens displaying an autogen reply URL.

![Image](https://github.com/user-attachments/assets/72dc53ae-eae7-4b51-993f-624cfd82f9b5)

**Step 2: Response Page**

Clicking Continue brings the user to the message page where they can see a copy of their message. A badge prominently displays the status.

![Reply Page](https://github.com/user-attachments/assets/5911f15c-f4d8-4bb1-b2a2-fe1f9d60a54d)

**When a case has been accepted:**
![Reply Page Accepted](https://github.com/user-attachments/assets/8939dae5-ed9f-4903-9364-18d7550bfe56)

### Tip Line Owner

**Step 1: New Message**

A new message is displayed with a blue indicator dot. 

![Inbox - New Message](https://github.com/user-attachments/assets/34889aa7-3324-4e1a-91eb-6e09c277a5dc)

**Step 2: Message Status**

Drilling in to the message shows actions which allow the tip line owner to change its status. Replies are automatically sent when the case status changes.

![Message - Waiting with Menu](https://github.com/user-attachments/assets/62c7be5c-551d-4eca-9501-d65ed8fbfaf9)

**Comment by brassy-endomorph** [comment]
Is there a requirement for this to be a modal? Because that would force the user to have JS enabled. Can this just be a second page? Like `/submit/success` or something?

**Comment by brassy-endomorph** [comment]
Second, if messages are (almost) always client-side encrypted, there's no point in displaying them as that block will be meaningless to the users. In cases where it's not encrypted, it's dangerous and could be used against them. The message should not be at all displayed back to the user once sent.

**Comment by brassy-endomorph** [comment]
More questions:

Do we _really_ need the "Received" date field to be displayed back to the submitter? That's another piece of metadata we're leaking if we do, and it also is annoying because of time zones since the DB is default UTC and we'd have to store a full timestamp and then localize it for the user. Or have a tool tip saying "this server's time zone is X." Which would also mean having to have a way to set the server's timezone. This is surprisingly annoying and should probably be in its own ticket to discuss.

**Comment by glenn-sorrentino** [comment]
> Is there a requirement for this to be a modal? Because that would force the user to have JS enabled. Can this just be a second page? Like `/submit/success` or something?

We can try as its own page.

**Comment by glenn-sorrentino** [comment]
> More questions:
> 
> Do we _really_ need the "Received" date field to be displayed back to the submitter? That's another piece of metadata we're leaking if we do, and it also is annoying because of time zones since the DB is default UTC and we'd have to store a full timestamp and then localize it for the user. Or have a tool tip saying "this server's time zone is X." Which would also mean having to have a way to set the server's timezone. This is surprisingly annoying and should probably be in its own ticket to discuss.

We can remove the date from the submitter view, but tip line owners will need to be able to filter messages by date, so keeping them will be important.

**Comment by brassy-endomorph** [comment]
> Changing the case's status sends a predefined reply visible on the message page to both tip line owner and whistleblower.

Who is allowed to set this? Each user? Instance admins?

**Comment by glenn-sorrentino** [comment]
Whoever receives the message.Message ID: ***@***.***&gt;

**Comment by brassy-endomorph** [comment]
If a user doesn't have message text set for a particular message status, then no text should be displayed, correct?

**Comment by brassy-endomorph** [comment]
It's perhaps not clear. Was the intention to have a history of all status changes? Or just the latest status change?

**Comment by glenn-sorrentino** [comment]
> It's perhaps not clear. Was the intention to have a history of all status changes? Or just the latest status change?

No, don't think we need a history of changes.

**Comment by glenn-sorrentino** [comment]
> If a user doesn't have message text set for a particular message status, then no text should be displayed, correct?

We should have default messages defined:

- Waiting for Response: Your message has been received. Please allow 24-72 hours for a reply. You can check this page any time for an update. Messages expire after 30 days.
- Accepted: Thank you for contacting us. We're looking more into your case. If you left a contact method we'll reach out to you there, too.
- Declined: Thank you for contacting us. Unfortunately we aren't able to move forward with your case. Please check the Hush Line user directory to find someone else who might be able to help.
- Archived: Your case has been archived. Contact us again if you need more help.
