### ISSUE TITLE
Parse env vars into `Config` object before configuring `Flask` object

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#637]
**Is your feature request related to a problem? Please describe.**

We currently have a bit of logic in the `create_app` function that handles config parsing and validation, and we should pull this into a separate config object so that we can more easily plug in arbitrary values at runtime without having to rebuild the app.

**Describe the solution you'd like**

```python
CONFIG_EXTRA_PREFIX = "X_"
CONFIG_JSON_EXTRA_PREFIX = "X_JSON"

def load_config(env: Mapping[str, str] | None = None) -> Mapping[str, Any]:
  if not env:
    env = dict(os.environ)
  config = {}

  # all our known configs go here

  if "FOO" in env:
    config["RENAMED"] = datetime.strptime("%Y-%M-%d", env["FOO"])
    config["BAR"] = env['BAR']  # here bar depends on foo, but isn't always there

  ...

  # unknown configs that are supposed to be strings
  for k, v in env.items():
    if k.startswith(CONFIG_EXTRA_PREFIX):
      config[k[len(CONFIG_EXTRA_PREFIX):]] = v

  # unknown configs that might need to be boolean or numbers
  for k, v in env.items():
    if k.startswith(CONFIG_JSON_EXTRA_PREFIX):
      try:
        value = json.loads(v)
      except JSONDecodeError:
        raise ValueError("Key {k} has invalid JSON")  # hide original error to not log secrets
      
      config[k[len(CONFIG_JSON_EXTRA_PREFIX):]] = value

  return config

app.config.from_mapping(load_config())
```

This method can easily be extended to look for a) env vars and then b) docker secrets with some clear override pattern. If nothing else, this should at least be pulled into its own module however we do it because there is about to be an explosion of env vars with some upcoming PRs and our config is a bit haphazard currently.

This method (and similar) also have the advantage that we're always working on a `Mapping` and not the raw `os.environ` which means slightly less weird patching and fixtures in the tests.

**Describe alternatives you've considered**

There are so many ways to do this that enumerating them all would be a total pain.

**Comment by brassy-endomorph** [comment]
Per discussion in chat about using an object to get type safety over just a `dict`.

1. We immediately lose all type safety when we add the fields to the `flask.config` `dict`
2. With a "flat" object, we cannot use the type system to express dependencies between two config values, e.g., if `FOO` is set, then `BAR` will always be set/not-null/non-empty
3. We can make a complex well-typed hierarchical config structure of nested objects, but that will only ever be internal to the `Config` class since the class is only instantiated once then immediately used to dump to an untyped dict

**Comment by brassy-endomorph** [comment]
Noting that we probably want to have a way to parse multiple types of data sources so that if we have physical hardware out in the world, it can configure new secret keys and such and write them to disk, then read them back on start up.

**Comment by micahflee** [comment]
I think this would be a good change. The config parsing login in `create_app` is getting gnarly.

> Noting that we probably want to have a way to parse multiple types of data sources so that if we have physical hardware out in the world, it can configure new secret keys and such and write them to disk, then read them back on start up.

For the personal server, I think we need to consider a robust way of providing updates that can include new config vars, but that's probably outside of the Hush Line app itself. (For example, make a hushline debian package that installs updated .env files for Docker Compose to use, or do all the updates to the project within a git repo like how Homebrew works, etc).

But in any of these cases, I think that ultimately the personal server will run the app in a container, and the secrets/vars will be provided to the container via environment variables.

**Comment by brassy-endomorph** [comment]
Sure, I mean "the app" in the loosest sense because something like cryptographic material would needed to be created per install and couldn't be passed as a default in the deb package.
