### ISSUE TITLE
Integrate alias feature with paid tiers

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#645]
**Is your feature request related to a problem? Please describe.**

When #595 was merged, it didn't include gating the Aliases feature on a paid subscription. This ticket attempts to answer open questions related to that.

**Questions**

- Should the `Alias` tab on the settings page be visible or absent when a user doesn't have a paid subscription?
- If the Alias tab is visible, what copy should it have? "This is only available for paid users. Plz upgrade."
- For "personal server" mode or self-hosted, should this feature be configurable? As in, an admin can say "all users get it or none regardless of Stripe"? If so, we need a config flag for that

**Comment by glenn-sorrentino** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> 
> 
> When #595 was merged, it didn't include gating the Aliases feature on a paid subscription. This ticket attempts to answer open questions related to that.
> 
> 
> 
> **Questions**
> 
> 
> 
> - Should the `Alias` tab on the settings page be visible or absent when a user doesn't have a paid subscription?

No subscription = no aliases tab

> - If the Alias tab is visible, what copy should it have? "This is only available for paid users. Plz upgrade."
> 
> - For "personal server" mode or self-hosted, should this feature be configurable? As in, an admin can say "all users get it or none regardless of Stripe"? If so, we need a config flag for that 

No, this is just a paid thing for the managed service.

**Comment by brassy-endomorph** [comment]
> No, this is just a paid thing for the managed service.

Disabling features if users don't pay for the hosted version feels rather not in the spirit of FOSS. Is there a reason someone self hosting shouldn't be able to enable aliases on their instance?

**Comment by glenn-sorrentino** [comment]
> > No, this is just a paid thing for the managed service.
> 
> 
> 
> Disabling features if users don't pay for the hosted version feels rather not in the spirit of FOSS. Is there a reason someone self hosting shouldn't be able to enable aliases on their instance?

Fair enough about single-tenant users or Personal Servers. Let's make it enabled by default for them, and gated on the managed service.

**Comment by brassy-endomorph** [comment]
Follow up from a conversation. We can probably fully remove the `is_personal_server` flag and have all the configs that define a current hardware set up defined via 1-3 flags. This means that enabling payment via the stripe env vars would set an internal flag like "is_payment_enabled" that then interplays with something called `ALIASES_ENABLED` which is `never`, `always` (default), or `subscription`.
