### ISSUE TITLE
Add Logo Uploads

### ISSUE THREAD

**Issue by glenn-sorrentino** [scidsg/hushline#726]
## End User Requirements

- An admin can upload a PNG
- The width/height should be adjustable, but set to 160px x 48px (@2x the rendered size in the browser) in the CSS
- The admin can remove the logo

## Infra
Digital Ocean Spaces should be used.

## No Logo Uploaded
![Page - Settings-no logo](https://github.com/user-attachments/assets/579a1184-8530-4895-9b1a-f006716b6086)

## Logo Uploaded
![Page - Settings](https://github.com/user-attachments/assets/4e6cef3c-0d67-43a2-b09c-8afa173c8464)

**Comment by brassy-endomorph** [comment]
> The width/height should be adjustable

What does this mean? As in, the app alters the image or that the CSS adjusts it for us?

Also, in the screenshot it shows lolo + name. Is this something we want? Like `[Psst...] Safe` or just `[Psst...]` ?

**Comment by glenn-sorrentino** [comment]
> > The width/height should be adjustable
> 
> 
> 
> What does this mean? As in, the app alters the image or that the CSS adjusts it for us?
> 

That's just to say the dimension requirements may change. 

> 
> Also, in the screenshot it shows logo + name. Is this something we want? Like `[Psst...] Safe` or just `[Psst...]` ?

We want logo + text.

**Comment by brassy-endomorph** [comment]
Closed by #730
