### ISSUE TITLE
Accessing `/register` and `/login` using onion address crashes the app

### ISSUE THREAD

**Issue by glenn-sorrentino** [scidsg/hushline#830]
## Issue 
Missing `SECRET_KEY` Causes Crashes on Onion Service

## Description
Some routes, such as login and register, crash on the Onion service with the following error:

```
[app-onion] [2024-12-16 21:27:20] [2024-12-16 21:27:20 +0000] [9] [INFO] Starting gunicorn 22.0.0
[app-onion] [2024-12-16 21:27:20] [2024-12-16 21:27:20 +0000] [9] [INFO] Listening at: http://0.0.0.0:8080 (9)
[app-onion] [2024-12-16 21:27:20] [2024-12-16 21:27:20 +0000] [9] [INFO] Using worker: sync
[app-onion] [2024-12-16 21:27:21] [2024-12-16 21:27:21 +0000] [12] [INFO] Booting worker with pid: 12
[app-onion] [2024-12-16 21:58:30] 2024-12-16 21:58:30,527:ERROR:Exception on /register [GET]
[app-onion] [2024-12-16 21:58:30] RuntimeError: The session is unavailable because no secret key was set.
[app-onion] [2024-12-16 21:58:31] 2024-12-16 21:58:31,938:ERROR:Exception on /favicon.ico [GET]
[app-onion] [2024-12-16 21:58:31] werkzeug.exceptions.NotFound: 404 Not Found
[app-onion] [2024-12-16 23:53:39] 2024-12-16 23:53:39,511:ERROR:Exception on /register [GET]
[app-onion] [2024-12-16 23:53:39] RuntimeError: The session is unavailable because no secret key was set.
[app-onion] [2024-12-17 00:20:18] 2024-12-17 00:20:18,968:ERROR:Exception on /login [GET]
[app-onion] [2024-12-17 00:20:18] RuntimeError: The session is unavailable because no secret key was set.
[app-onion] [2024-12-17 02:03:30] 2024-12-17 02:03:30,984:ERROR:Exception on /register [GET]
[app-onion] [2024-12-17 02:03:30] RuntimeError: The session is unavailable because no secret key was set.
```

This occurs because the `SECRET_KEY` is not properly set when running the app in the Onion environment. Pages that rely on sessions or CSRF protection fail, while others load fine.

## Steps to Reproduce
	1.	Access the Onion service URL.
	2.	Navigate to `/login` or `/register`.
	3.	Observe the application crash.

## Actual Behavior
Routes that use sessions or CSRF tokens crash due to a missing `SECRET_KEY`.

## Potential Fix
Ensure `SECRET_KEY` is consistently set across all environments, including the Onion service.

**Comment by micahflee** [comment]
This is a trickier problem than it seems. I've confirmed that `SECRET_KEY` is set in the onion service containers.

I've confirmed that the crash is happening inside Flask's `sessions.py` code here:

```py
class NullSession(SecureCookieSession):
    """Class used to generate nicer error messages if sessions are not
    available.  Will still allow read-only access to the empty session
    but fail on setting.
    """

    def _fail(self, *args: t.Any, **kwargs: t.Any) -> t.NoReturn:
        raise RuntimeError(
            "The session is unavailable because no secret "
            "key was set.  Set the secret_key on the "
            "application to something unique and secret."
        )

    __setitem__ = __delitem__ = clear = pop = popitem = update = setdefault = _fail  # type: ignore # noqa: B950
    del _fail
```

This makes me think that this is related to some sort of regression caused by #806, though I'm not sure what it could be.

Since it happens on the onion service but not the clearnet service, it's possible it has something to do with HTTP instead of HTTPS, but if that were the case it should be reproducible while running a dev server locally, and it's not.
